### ISSUE TITLE
v0.004-alpha: [BUG] editing mode: content

### ISSUE THREAD

**Issue by arcade-legend** [Skurdt/3DArcade#12]
Hi

My first attempt to make platform/emulator/game list is failing because of a bug.

- When trying to select the platform I just created and an emulator override, clicking apply and then save, the settings are not stored.
So when going back to content editing mode, the values for "platform" and "emulator override" were not saved.

- is it correct you choose "gameinternal" for all libretro cores and "gameexternal" for all external exe files of emulators?

- how to run a game when the platform/emulator/game list is chosen correctly and you stand in front of a cabinet?

![afbeelding](https://user-images.githubusercontent.com/85412588/121081797-7d5ed980-c7dd-11eb-9833-044a69c5b7be.png)

**Comment by Skurdt** [comment]
In edit content mode, you only have to select a platform and set an id.
Haven't had a chance to rework the dropdown but the interaction type there is an override. It's only there to give the ability to use FPSArcadeConfiguration and set an id to an existing arcade in order to switch scenes on model selection, and these are also not listed here yet. You most likely want to leave it at default.

The platform configuration holds the emulator to use. The emulator override is only to launch a specific game with a different emulator than what the specified platform uses.

Now for things not saving I'm not sure, I'll have to try and reproduce the issue.

**Comment by arcade-legend** [comment]
Can you also tell me how to run a game when standing in front of a cabinet?
Is it a key or a mouse action? My libretro cores are copied to the "cores" folder and my roms folder is setup too.

I can only test this in the next update because saving platform in content edit mode does not work here.
I think that's the only thing left to finally see it run!

**Comment by Skurdt** [comment]
Saving platforms work, you can see in the alpha4 video that I add a gamelist, a platform, an emulator and spawn a game for the atari2600. And then remove them at the end. So I'm pretty sure the entire chain is working.

**Comment by arcade-legend** [comment]
Please download my specific project in which i made a mame 0.223 game list. And a platform "mame test"
I added a cabinet at the left.
Please try to save the platform "mame test" on that cabinet.
It doesn't work :(

https://we.tl/t-tkYEGRBNVG

**Comment by Skurdt** [comment]
It's just a UI bug, targeting a cab that uses an other platform and back shows the correct value.
Starting the game works fine.

**Comment by arcade-legend** [comment]
Maybe a stupid question, but how to start a game?

**Comment by Skurdt** [comment]
Left click

**Comment by Skurdt** [comment]
Closing this for now, it may or may not be fixed starting 3e25bfa2641d687b522a1b3b021385298c87048c ...
Needs more testing.
