### ISSUE TITLE
v0.005-alpha: [BUG?] Mame2003PlusXml

### ISSUE THREAD

**Issue by arcade-legend** [Skurdt/3DArcade#20]
Hi

Not sure which XML files are accepted by Mame2003PlusXml for generating a game list?
I made an XML file for latest mame using the command line: mame -listxml > listxml.xml
Then I opened this XML file "listxml.xml" in 3DArcade using Mame2003PlusXml but nothing happens. No game list is generated. I waited some minutes.

Is this a bug or can you tell me what versions of MAME will work using Mame2003PlusXml?

If Mame2003PlusXml is not accepting new MAME versions, would it be possible to add a feature "MAME XML File" which accepts any recent MAME XML file (the XML file structure in MAME doesn't change anymore last years) in order to filter this file using this tool (MAME XML Cleaner: https://www.systempixel.fr/mame-xml-cleaner/) and load it in 3DArcade to make a filtered game list based on the XML file?

thx

**Comment by arcade-legend** [comment]
I ask this because I wanted to test a nice tool I found to clean MAME XML files: https://www.systempixel.fr/mame-xml-cleaner/

**Comment by Skurdt** [comment]
mame2003_plus is a version of mame based on the mame2003 code but with added games and is actively developed/maintained.

The xml from 2003+ is not the same as current mame releases, trying to read a mame xml using the "Mame2003PlusXml" option
will not work. 

To generate a list from it you need to start a game, go into the mame menu (think it's the C key) and select the generate xml from there, it should appear somewhere in the libretro~ folder hierarchy (most likely mame2003_plus/system or save, don't remember).

And yes, I'll be adding an other option to select the xml instead of generating one from the exe, so you'll be able to use that tool, RomLister, or whatever else is available out there (there's a bunch).

**Comment by arcade-legend** [comment]
Ok, everything is clear.
